# Generated by Django 3.1.4 on 2020-12-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
