version: "3.7"

services:
  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - db_volume:/var/lib/mysql
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    environment:
      - MYSQL_DATABASE=django
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_USER_FILE=/run/secrets/MYSQL_USER
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD

  django_container:
    image: django_test:1
    networks:
      - network
    volumes:
      - static-volume:/home/like-pinterest/staticfiles
      - media-volume:/home/like-pinterest/uploads
    secrets:
      - DJANGO_SECRET_KEY
      - MYSQL_USER
      - MYSQL_PASSWORD

  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/django/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80

networks:
  network:

volumes:
  static-volume:
  media-volume:
  db_volume:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MYSQL_USER:
    external: true
  MYSQL_PASSWORD:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true
